"""Per-app ForwardAuth middleware generation for Traefik.

This module generates per-app Traefik middleware configuration for apps
that need custom header mappings in Forward Auth.
"""

from typing import Any

import yaml


def generate_forwardauth_middleware(metadata: dict[str, Any]) -> str | None:
    """Generate per-app ForwardAuth middleware for Traefik.

    Args:
        metadata: Package metadata dictionary

    Returns:
        YAML content for Traefik dynamic config, or None if not needed
    """
    routing_config = metadata.get("routing")
    if not routing_config:
        return None

    # Get auth configuration
    auth_config = routing_config.get("auth")
    if not auth_config:
        return None

    # Handle both nested dict format and flat string format
    if isinstance(auth_config, dict):
        auth_mode = auth_config.get("mode", "forward_auth")
        forward_auth = auth_config.get("forward_auth")
    else:
        # Flat format: auth is just the mode string
        auth_mode = auth_config
        forward_auth = routing_config.get("forward_auth")

    # Only generate for forward_auth mode
    if auth_mode != "forward_auth":
        return None

    if not forward_auth:
        return None

    headers = forward_auth.get("headers")
    if not headers:
        return None  # Use default authelia@file middleware

    app_id = metadata.get("app_id", "")

    # Build response headers list from the header mapping keys
    # The mapping is: Authelia-header -> App-expected-header
    # We need the Authelia headers (the keys) in the response
    auth_response_headers = list(headers.keys())

    middleware_config = {
        "http": {
            "middlewares": {
                f"authelia-{app_id}": {
                    "forwardAuth": {
                        "address": "http://authelia:9091/api/authz/forward-auth",
                        "trustForwardHeader": True,
                        "authResponseHeaders": auth_response_headers,
                    }
                }
            }
        }
    }

    # Generate YAML with header comments
    lines = [
        f"# Per-app ForwardAuth middleware for {app_id}",
        "# Generated by container-packaging-tools",
        f"# Installed to /etc/halos/traefik-dynamic.d/{app_id}.yml",
        "",
        yaml.dump(middleware_config, default_flow_style=False, sort_keys=False),
    ]

    return "\n".join(lines)
