"""Prestart script generation for container apps."""

from typing import Any

from generate_container_packages.labels import find_port_env_var
from generate_container_packages.loader import AppDefinition


def get_homarr_url_expression(
    web_ui: dict[str, Any], default_config: dict[str, str] | None
) -> str | None:
    """Generate the HOMARR_URL shell expression.

    Args:
        web_ui: Web UI configuration dictionary
        default_config: Default configuration dictionary

    Returns:
        Shell expression for HOMARR_URL, or None if web_ui is disabled
    """
    if not web_ui or not web_ui.get("enabled", False):
        return None

    protocol = web_ui.get("protocol", "http")
    port = web_ui.get("port", 80)
    path = web_ui.get("path", "")

    # Find port environment variable
    port_var = find_port_env_var(default_config)

    # Build port expression
    if port_var:
        port_expr = f"${{{port_var}:-{port}}}"
    else:
        port_expr = str(port)

    # Build URL expression
    url = f"{protocol}://${{HOSTNAME}}.local:{port_expr}"
    if path and path != "/":
        # Ensure path starts with /
        if not path.startswith("/"):
            path = "/" + path
        url += path

    return url


def generate_prestart_script(app_def: AppDefinition) -> str:
    """Generate prestart script content for a container app.

    The prestart script:
    1. Creates the runtime env directory
    2. Loads existing env files to access config values
    3. Computes runtime values (HOSTNAME, HALOS_DOMAIN, HOMARR_URL)
    4. Writes computed values to runtime.env

    Args:
        app_def: Application definition

    Returns:
        Bash script content as string
    """
    metadata = app_def.metadata
    package_name = metadata.get("package_name", "unknown")
    web_ui = metadata.get("web_ui", {})
    traefik = metadata.get("traefik", {})
    default_config = metadata.get("default_config", {})

    # Paths
    etc_dir = f"/etc/container-apps/{package_name}"
    run_dir = f"/run/container-apps/{package_name}"
    runtime_env = f"{run_dir}/runtime.env"

    # Build script
    lines = [
        "#!/bin/bash",
        f"# Prestart script for {package_name}",
        "# Auto-generated by container-packaging-tools",
        "set -e",
        "",
        "# Create runtime directory",
        f'RUNTIME_ENV="{runtime_env}"',
        'mkdir -p "$(dirname "$RUNTIME_ENV")"',
        "",
        "# Load config values from env files",
        "set -a",
        f'[ -f "{etc_dir}/env.defaults" ] && . "{etc_dir}/env.defaults"',
        f'[ -f "{etc_dir}/env" ] && . "{etc_dir}/env"',
        "set +a",
        "",
        "# Set hostname",
        'HOSTNAME="$(hostname -s)"',
        'echo "HOSTNAME=$HOSTNAME" > "$RUNTIME_ENV"',
    ]

    # Add HALOS_DOMAIN for traefik-enabled apps
    # (explicit traefik config or implicit from web_ui.enabled)
    has_traefik = bool(traefik) or (web_ui and web_ui.get("enabled", False))
    if has_traefik:
        lines.extend(
            [
                "",
                "# Set HALOS_DOMAIN for Traefik routing",
                'HALOS_DOMAIN="${HOSTNAME}.local"',
                'echo "HALOS_DOMAIN=$HALOS_DOMAIN" >> "$RUNTIME_ENV"',
            ]
        )

    # Add HOMARR_URL if web_ui is enabled
    homarr_url_expr = get_homarr_url_expression(web_ui, default_config)
    if homarr_url_expr:
        lines.extend(
            [
                "",
                "# Compute Homarr URL",
                f'HOMARR_URL="{homarr_url_expr}"',
                'echo "HOMARR_URL=$HOMARR_URL" >> "$RUNTIME_ENV"',
            ]
        )

    # Final newline
    lines.append("")

    return "\n".join(lines)
