"""App registry file generation for homarr-container-adapter.

Generates TOML registry files that define apps for the unified app registry
at /etc/halos/webapps.d/. This replaces Docker-label-based discovery.
"""

from pathlib import Path
from typing import Any

from generate_container_packages.labels import DEFAULT_CATEGORY, TAG_TO_CATEGORY


def get_category_from_tags(tags: list[str]) -> str:
    """Derive category from debtags.

    Args:
        tags: List of debtags

    Returns:
        Category string for the app registry
    """
    for tag in tags:
        if tag in TAG_TO_CATEGORY:
            return TAG_TO_CATEGORY[tag]
    return DEFAULT_CATEGORY


def _escape_toml_string(value: str) -> str:
    """Escape a string for use in TOML.

    Args:
        value: String to escape

    Returns:
        Escaped string safe for TOML basic string format
    """
    return value.replace("\\", "\\\\").replace('"', '\\"')


def generate_registry_toml(
    metadata: dict[str, Any],
    compose: dict[str, Any],
    hostname: str,
    icon_path: Path | None = None,
) -> str | None:
    """Generate TOML registry file content for an app.

    Args:
        metadata: Package metadata dictionary
        compose: Docker compose configuration
        hostname: System hostname for URL generation (e.g., from $HOSTNAME)
        icon_path: Path to auto-detected icon file (optional)

    Returns:
        TOML content string, or None if web_ui is not enabled
    """
    web_ui = metadata.get("web_ui")

    # Return None if web_ui is not configured or disabled
    if not web_ui or not web_ui.get("enabled", False):
        return None

    package_name = metadata.get("package_name", "")
    app_name = metadata.get("name", package_name)
    description = metadata.get("description", "")
    tags = metadata.get("tags", [])
    category = get_category_from_tags(tags)

    # Build icon URL
    icon_url = None
    if metadata.get("icon"):
        icon = metadata.get("icon", "")
        ext = icon.split(".")[-1] if "." in icon else "png"
        icon_url = f"/usr/share/pixmaps/{package_name}.{ext}"
    elif icon_path is not None:
        ext = icon_path.suffix.lstrip(".")
        icon_url = f"/usr/share/pixmaps/{package_name}.{ext}"

    # Get the primary service name from docker-compose
    services = compose.get("services", {})
    container_name = None
    if services:
        # Use the first service name as the container name
        # Container apps typically have one main service
        container_name = list(services.keys())[0]

    # Build the TOML content
    escaped_name = _escape_toml_string(app_name)
    lines = [
        f"# {app_name} - App Registry Entry",
        "# Generated by container-packaging-tools",
        f"# Installed to /etc/halos/webapps.d/{package_name}.toml",
        "",
        f'name = "{escaped_name}"',
        "# URL is computed at build time from web_ui config",
    ]

    # Build URL from web_ui config
    protocol = web_ui.get("protocol", "http")
    port = web_ui.get("port", 80)
    path = web_ui.get("path", "/")
    if not path.startswith("/"):
        path = "/" + path

    # Standard URL format
    if (protocol == "http" and port == 80) or (protocol == "https" and port == 443):
        url = f"{protocol}://{hostname}{path}"
    else:
        url = f"{protocol}://{hostname}:{port}{path}"

    lines.append(f'url = "{url}"')

    if description:
        escaped_desc = _escape_toml_string(description)
        lines.append(f'description = "{escaped_desc}"')

    if icon_url:
        lines.append(f'icon_url = "{icon_url}"')

    lines.append(f'category = "{category}"')

    # Visibility for Homarr dashboard (default: false)
    visible = web_ui.get("visible", False)
    lines.append(f"visible = {str(visible).lower()}")

    lines.append("")
    lines.append("[type]")
    if container_name:
        lines.append(f'container_name = "{container_name}"')
    else:
        lines.append("# No container_name - external app")

    # Get layout configuration with defaults
    layout = metadata.get("layout", {})
    priority = layout.get("priority", 50)
    width = layout.get("width", 1)
    height = layout.get("height", 1)
    x_offset = layout.get("x_offset")
    y_offset = layout.get("y_offset")

    lines.append("")
    lines.append("[layout]")
    lines.append(f"priority = {priority}")
    lines.append(f"width = {width}")
    lines.append(f"height = {height}")
    if x_offset is not None:
        lines.append(f"x_offset = {x_offset}")
    if y_offset is not None:
        lines.append(f"y_offset = {y_offset}")
    lines.append("")

    return "\n".join(lines)
