"""App registry file generation for homarr-container-adapter.

Generates TOML registry files that define apps for the unified app registry
at /etc/halos/webapps.d/. This replaces Docker-label-based discovery.
"""

from pathlib import Path
from typing import Any

from generate_container_packages.labels import DEFAULT_CATEGORY, TAG_TO_CATEGORY


def get_category_from_tags(tags: list[str]) -> str:
    """Derive category from debtags.

    Args:
        tags: List of debtags

    Returns:
        Category string for the app registry
    """
    for tag in tags:
        if tag in TAG_TO_CATEGORY:
            return TAG_TO_CATEGORY[tag]
    return DEFAULT_CATEGORY


def generate_registry_toml(
    metadata: dict[str, Any],
    compose: dict[str, Any],
    icon_path: Path | None = None,
) -> str | None:
    """Generate TOML registry file content for an app.

    Args:
        metadata: Package metadata dictionary
        compose: Docker compose configuration
        icon_path: Path to auto-detected icon file (optional)

    Returns:
        TOML content string, or None if web_ui is not enabled
    """
    web_ui = metadata.get("web_ui")

    # Return None if web_ui is not configured or disabled
    if not web_ui or not web_ui.get("enabled", False):
        return None

    package_name = metadata.get("package_name", "")
    app_name = metadata.get("name", package_name)
    description = metadata.get("description", "")
    tags = metadata.get("tags", [])
    category = get_category_from_tags(tags)

    # Build icon URL
    icon_url = None
    if metadata.get("icon"):
        icon = metadata.get("icon", "")
        ext = icon.split(".")[-1] if "." in icon else "png"
        icon_url = f"/usr/share/pixmaps/{package_name}.{ext}"
    elif icon_path is not None:
        ext = icon_path.suffix.lstrip(".")
        icon_url = f"/usr/share/pixmaps/{package_name}.{ext}"

    # Get the primary service name from docker-compose
    services = compose.get("services", {})
    container_name = None
    if services:
        # Use the first service name as the container name
        # Container apps typically have one main service
        container_name = list(services.keys())[0]

    # Build the TOML content
    lines = [
        f"# {app_name} - App Registry Entry",
        "# Generated by container-packaging-tools",
        f"# Installed to /etc/halos/webapps.d/{package_name}.toml",
        "",
        f'name = "{app_name}"',
        "# URL is computed at runtime from web_ui config",
        "# Using halos.local as the default hostname",
    ]

    # Build URL from web_ui config
    protocol = web_ui.get("protocol", "http")
    port = web_ui.get("port", 80)
    path = web_ui.get("path", "/")
    if not path.startswith("/"):
        path = "/" + path

    # Standard URL format
    if (protocol == "http" and port == 80) or (protocol == "https" and port == 443):
        url = f"{protocol}://halos.local{path}"
    else:
        url = f"{protocol}://halos.local:{port}{path}"

    lines.append(f'url = "{url}"')

    if description:
        lines.append(f'description = "{description}"')

    if icon_url:
        lines.append(f'icon_url = "{icon_url}"')

    lines.append(f'category = "{category}"')

    # Default priority (40-59 range for container apps)
    lines.append("priority = 50")

    lines.append("")
    lines.append("[type]")
    if container_name:
        lines.append(f'container_name = "{container_name}"')
    else:
        lines.append("# No container_name - external app")

    lines.append("")
    lines.append("# Layout is optional - apps will be auto-positioned by priority")
    lines.append("# Uncomment and customize if explicit positioning is needed:")
    lines.append("# [layout]")
    lines.append("# width = 1")
    lines.append("# height = 1")
    lines.append("# x_offset = 0")
    lines.append("# y_offset = 0")
    lines.append("")

    return "\n".join(lines)
