name: 'Check Version Consistency'
description: 'Verify VERSION file matches pyproject.toml and __init__.py versions'

runs:
  using: 'composite'
  steps:
    - name: Check version consistency
      shell: bash
      run: |
        set -euo pipefail

        # Read canonical version from VERSION file
        if [ ! -f "VERSION" ]; then
          echo "ERROR: VERSION file not found"
          exit 1
        fi
        VERSION_FILE=$(tr -d '[:space:]' < VERSION)
        if [ -z "$VERSION_FILE" ]; then
          echo "ERROR: VERSION file is empty"
          exit 1
        fi
        echo "VERSION file:    $VERSION_FILE"

        # Check pyproject.toml exists
        if [ ! -f "pyproject.toml" ]; then
          echo "ERROR: pyproject.toml not found"
          exit 1
        fi

        # Extract version from pyproject.toml
        PYPROJECT_VERSION=$(grep -m1 '^version = "' pyproject.toml | sed 's/version = "\([^"]*\)".*/\1/' || true)
        if [ -z "$PYPROJECT_VERSION" ]; then
          echo "ERROR: Could not extract version from pyproject.toml"
          exit 1
        fi
        echo "pyproject.toml:  $PYPROJECT_VERSION"

        # Check __init__.py exists
        INIT_FILE="src/generate_container_packages/__init__.py"
        if [ ! -f "$INIT_FILE" ]; then
          echo "ERROR: $INIT_FILE not found"
          exit 1
        fi

        # Extract version from __init__.py
        INIT_VERSION=$(grep -m1 '__version__ = "' "$INIT_FILE" | sed 's/__version__ = "\([^"]*\)".*/\1/' || true)
        if [ -z "$INIT_VERSION" ]; then
          echo "ERROR: Could not extract version from $INIT_FILE"
          exit 1
        fi
        echo "__init__.py:     $INIT_VERSION"

        # Compare
        FAILED=0

        if [ "$VERSION_FILE" != "$PYPROJECT_VERSION" ]; then
          echo ""
          echo "Version mismatch: VERSION ($VERSION_FILE) != pyproject.toml ($PYPROJECT_VERSION)"
          FAILED=1
        fi

        if [ "$VERSION_FILE" != "$INIT_VERSION" ]; then
          echo ""
          echo "Version mismatch: VERSION ($VERSION_FILE) != __init__.py ($INIT_VERSION)"
          FAILED=1
        fi

        if [ $FAILED -eq 1 ]; then
          echo ""
          echo "Use './run bumpversion [patch|minor|major]' to update versions consistently."
          exit 1
        fi

        echo ""
        echo "Version check passed: $VERSION_FILE"
